SELECT AIN.ANIMAL_ID, AIN.NAME
FROM ANIMAL_INS AS AIN
JOIN (
    SELECT ANIMAL_ID, DATETIME
    FROM ANIMAL_OUTS
)AS AOUT
ON AIN.ANIMAL_ID=AOUT.ANIMAL_ID
WHERE AIN.DATETIME>AOUT.DATETIME
ORDER BY AIN.DATETIME ASC